apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-app
  namespace: application  # Assuming 'application' namespace for your app
spec:
  replicas: 2  # Number of replicas (pods) for high availability
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1  ### One extra pod can be created during the update
      maxUnavailable: 0  ## Ensures no pods are taken down during the update
  selector:
    matchLabels:
      app: sre-app
  template:
    metadata:
      labels:
        app: sre-app
    spec:
      containers:
        - name: sre-app
          image: "${{ secrets.DOCKER_USERNAME }}/sre-app:${IMAGE_TAG}"  # Dynamic image tag
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "128m"
            limits:
              memory: "256Mi"
              cpu: "256"
