apiVersion: apps/v1
kind: Deployment
metadata:
  name: personio-app
  namespace: application  # Assuming 'application' namespace for your app
spec:
  replicas: 2  # Number of replicas (pods) for high availability
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1  ##### One extra pod can be created during the update
      maxUnavailable: 0  ## Ensures no pods are taken down during the update
  selector:
    matchLabels:
      app: personio-app
  template:
    metadata:
      labels:
        app: personio-app
    spec:
      containers:
        - name: personio-app
          image: "${{ var.DOCKER_USERNAME }}/personio-app:${{ var.IMAGE_TAG }}"  # Dynamic image tag
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "128m"
            limits:
              memory: "256Mi"
              cpu: "256"
