apiVersion: v1
kind: Service
metadata:
  name: personio-app
  namespace: application  # Assuming 'application' namespace for your app
spec:
  type: NodePort
  selector:
    app: personio-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001
