name: Terraform Apply

on:
  pull_request:
    types:
      - closed  # Trigger only when the PR is closed (merged or rejected)


  # Allow manual trigger via GitHub UI (workflow_dispatch)
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1  # Mumbai region
  CLUSTER_NAME: sre-cluster
  TF_STATE_BUCKET: personio-aws-infra-statebucket  # Replace with your S3 bucket name
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: sre-app
  IMAGE_TAG: latest

jobs:
  terraform-apply:
    if: ${{ github.event.pull_request.merged == true }}  # Only if the PR is merged
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0  # Consistent version

    - name: Terraform Init
      run: |
        cd terraform
        terraform init -backend-config="bucket=${{ env.TF_STATE_BUCKET }}" \
                       -backend-config="key=terraform/state/terraform.tfstate" \
                       -backend-config="region=${{ env.AWS_REGION }}"

    - name: Download tfplan artifact from plan.yml
      uses: actions/download-artifact@v4
      with:
        name: tfplan  # Name of the artifact from plan.yml
        path: terraform  # Path where the plan artifact will be downloaded

    - name: Terraform Apply
      run: |
        cd terraform
        terraform apply -auto-approve terraform/tfplan  # Apply the downloaded plan

    - name: Terraform Apply Output
      run: terraform output  # Output any relevant results from the Terraform apply