name: Terraform Apply

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the 'main' branch

  # Allow manual trigger via GitHub UI (workflow_dispatch)
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1  # Mumbai region
  CLUSTER_NAME: sre-cluster
  TF_STATE_BUCKET: personio-aws-infra-statebucket  # Replace with your S3 bucket name
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: sre-app
  IMAGE_TAG: latest

jobs:
  terraform_apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-south-1"  # Mumbai region (Update if needed)

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Consistent version

      - name: List downloaded files
        run: ls -l ./terraform

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ env.TF_STATE_BUCKET }}" -backend-config="key=terraform/state/terraform.tfstate" -backend-config="region=${{ env.AWS_REGION }}"

#      - name: Download Terraform Plan Artifact
#        uses: actions/download-artifact@v4
#        with:
#          name: terraform-plan  # Name of the artifact uploaded in plan.yml
#          path: ./terraform

#      - name: Terraform Apply
#        run: terraform apply -auto-approve ./terraform/tfplan  # Applying the downloaded plan artifact

#      - name: Terraform Apply Output
#        run: terraform output  # Output any relevant results from the Terraform apply
