name: Terraform Plan

on:
  pull_request:
    branches:
      - main

env:
  AWS_REGION: ap-south-1  # Mumbai region
  CLUSTER_NAME: sre-cluster
  TF_STATE_BUCKET: personio-aws-infra-statebucket  # Replace with your S3 bucket name
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: sre-app
  IMAGE_TAG: latest

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # Build Docker Image
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
    
    - name: Push Docker image to DockerHub
      run: |
        docker push ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Initialize Terraform
      run: terraform init -backend-config="bucket=${{ env.TF_STATE_BUCKET }}" -backend-config="key=terraform/state/terraform.tfstate" -backend-config="region=${{ env.AWS_REGION }}"

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Upload Terraform Plan Artifact
      uses: actions/upload-artifact@v3
      with:
        name: terraform-plan
        path: tfplan

    - name: Comment Terraform Plan on GitHub PR
      uses: peter-evans/comment-pr@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          **Terraform Plan:**
          ```
          $(terraform show -no-color tfplan)
          ```
